version: '3.8'

services:
  hr-dashboard:
    image: ghcr.io/hienhoceo-dpsmedia/dpsmedia-hr-360:latest
    container_name: dps-hr-dashboard
    restart: always
    ports:
      - "6001:80"
    environment:
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    networks:
      - hr-network

networks:
  hr-network:
    driver: bridge
